### ISSUE TITLE
error importing directory / x86 darwin 

### ISSUE THREAD

**Issue by exdysa** [amiralitaheri/sd-gallery#3]
I launched the app (my excitement, brewing!) I clicked Import and I got a window to select for a directory. When I selected one, I got this:

<img width="1437" alt="Screen Shot 2024-06-02 at 21 58 08" src="https://github.com/amiralitaheri/sd-gallery/assets/91800957/92e4bf13-6e8a-4cbc-b0fc-cab35d7180d2">

And nothing happens. To be certain, I removed the app, re-downloaded and re-extracted the zip, and then dragged it into applications again. I also allowed it full disk access in Security preferences, which I shouldn't have to do to make it work. I guess I'm lucky I have a machine running windows too!

Heres an inspection recording of mouse activity triggering the result.
[Recording 6_2_2024 at 9_59_47 PM.json](https://github.com/user-attachments/files/15527968/Recording.6_2_2024.at.9_59_47.PM.json)

If there are log files for the program I'm not sure where they are. I didn't see anything in ~/.config...

Hope I have been helpful 🤍 

Update: I launched it again and it shows pictures now... but not all of them. And it still throws the same error warning. It seems to be grumpy, but reluctantly compliant...
<img width="1358" alt="Screen Shot 2024-06-02 at 22 15 06" src="https://github.com/amiralitaheri/sd-gallery/assets/91800957/dca96948-db52-4eba-a60d-9e65442959d4">

**Comment by amiralitaheri** [comment]
Hi @exdysa 
Thanks for using the app and sharing your issue and sorry for your bad experience.
I only tested the app on linux and windows machine. So the mac version was just there in case.

I will try my best to fix these issues. But beforehand I need to understand them correctly. So I will ask you a couple of questions.

1. In issue #2 you mentioned that the DB failed to initialized on mac device. and then In this issue you tried it on a windows machine but failed in importing process. Am I right?
2. The [Recording 6_2_2024 at 9_59_47 PM.json](https://github.com/user-attachments/files/15527968/Recording.6_2_2024.at.9_59_47.PM.json) seems to be corrupted and the file size is 0, could You possibly share it with me in another channel (Email, Telegram)?
3. It seems that the importing process of directory `05` failed and the number of files are relatively small, So could you share it as a Zip file? (FYI: I suspect that file names are the issue based on the image you shared)

**Comment by exdysa** [comment]
Hello! So to clarify, I never installed it on windows because it sort-of worked in MacOS? I have folders of images sorted by month of generation. You can see in this picture I imported folders 05 and 06, then attempted to import the entire folder 2024, whereupon it worked all the way through 03 and 04, though it still threw error messages. I tried reloading/force reladoing multiple times and re-attempting the import/sync processes to no dice. I think it might be more efficient for me to un-break it and then turn over the offending file... as other than file name, maybe it is a corrupt header? Theres several gigs of images in these folders so sharing is a little rough. For example, theres 2300 images now in the database, most of which display correctly (yay) And I make several hundered more a day if all goes well.

As far as the .json file, well.. maybe better I just document the entire install and working process here.

- Downloaded the zip, dragged it to Applications
- Surprised to find the App just by itself vs usual drag/drop window. Dragged it to Applications (Thinking back, I may have launched accidentally in this process without noticing to trigger the launch exception.)
- Attempted to import 06 folder (most recent images), "An Error Occured -_-". Spinning Import wheel, nothing seemed to happen.
- Relaunched, retried import. Pressed import, sync a few more times. Made the recording inside the inspector and then saved it directly from the inspector [in the Developer Tools menu ;)] then posted bug report. Things are very buggy in sd-prompt-reader and you mentioned that this app was untested so at this point I wasn't surprised. Didn't think to check the file size of my recording. My b.
- Attempted to import 05 folder. I got "An Error", spinning import wheel, spinning blue wheel on cursor, and no images, but after a reboot some images appeared??
- Here is where I started to go a bit mad and try to alternate reload/force reload and alternate tap Import/Sync. I didn't get anywhere but the few images you saw in that picture.
- Attempted to import the entire year's folder, which is a directory containing 03, 04, 05 and 06. Here the app was much more successful, though "An error" still occured after a little bit of time.... I let the app run anyway for a while. Nothing showed up right away, so I quit, then opened it again and got the 2000-something 03 and 04 folders into the database. Then I ran it again and left it alone for a while, restarted it and it had gone quite far.

<img width="1034" alt="Screen Shot 2024-06-03 at 13 22 44" src="https://github.com/amiralitaheri/sd-gallery/assets/91800957/ab8aa69b-b37f-489c-8d4b-f099daf8395d">
<img width="1148" alt="Screen Shot 2024-06-03 at 13 44 38" src="https://github.com/amiralitaheri/sd-gallery/assets/91800957/9f2129c0-4760-4f27-8426-7d6af1c1ce43">
<img width="1170" alt="Screen Shot 2024-06-03 at 13 45 31" src="https://github.com/amiralitaheri/sd-gallery/assets/91800957/5b465c95-f27d-446e-bb2d-15cb7b26b8ca">


Don't worry about the troubles, I'm quite pleased with the app so far regardless. Much faster and more stable than sd-prompt-reader/sd-prompt-reader-beta. I'll try to narrow down the file/s in the way, since technically you'd need to clone my entire drive to replicate the situation exactly...

**Comment by exdysa** [comment]
> Hi @exdysa Thanks for using the app and sharing your issue and sorry for your bad experience. I only tested the app on linux and windows machine. So the mac version was just there in case.
> 
> I will try my best to fix these issues. But beforehand I need to understand them correctly. So I will ask you a couple of questions.
> 
> 1. In issue [x86 darwin first launch exception #2](https://github.com/amiralitaheri/sd-gallery/issues/2) you mentioned that the DB failed to initialized on mac device. and then In this issue you tried it on a windows machine but failed in importing process. Am I right?
> 2. The [Recording 6_2_2024 at 9_59_47 PM.json](https://github.com/user-attachments/files/15527968/Recording.6_2_2024.at.9_59_47.PM.json) seems to be corrupted and the file size is 0, could You possibly share it with me in another channel (Email, Telegram)?
> 3. It seems that the importing process of directory `05` failed and the number of files are relatively small, So could you share it as a Zip file? (FYI: I suspect that file names are the issue based on the image you shared)

Ok! After much mac testing, I feel confident that the problem is larger than filename characters. Played with a lot of +/%/-/_ special characters (+ and % may be a problem), but theres a whole directory with none of those in it that simply will not load. Whats most odd is I put 4 working images from another folder into a problematic folder along with 1 of the images that wouldn't load. The directory imported, and the bottom right showed "SUCCESS" with a count of 5 images.... but only displayed the 4 working images? So there is something more than my awful wildcard experiments going on here ;) Example Included, see if you can replicate the behavior by extracting this directory on its own -

[06.zip](https://github.com/user-attachments/files/15538453/06.zip)

For context, the first 4 beginning with zero use a Comfy workflow that has sd-prompt-saver inside of it, and I am fairly certain the metadata is correctly formatted because of this. However the 5th has a different workflow and terminates with the default Comfy "Save Image" node.

If I drag and drop the problem file into Comfy the workflow loads correctly (have just tested this so), but the metadata for this workflow never reads in sd-prompt-reader. Whats more, the workflow is enormous [pushing 70 nodes as of today]... yet the filename is similar to the rest. So, it could be the workflow is too big, or the metadata formatting breaks it. Maybe both, and more!

Process wise, each time I loaded a folder I removed the directory, relaunched the app, then synced or imported the folder anew. The app had a tendency to fail with an error and show nothing when a troublesome image was inside of it, but if I /reloaded/ or relaunched the app it would show the folder in the directory list, but empty of files. Further syncs would throw "An error". I didn't import the whole "2024" folder, just the one "06" directory

Bonus! I got a MacOS crash report after closing the program from one of the failed directory loads. Perhaps theres some insight?
[sdgmacoslog.txt](https://github.com/user-attachments/files/15538497/sdgmacoslog.txt)

Oh, and lastly, I very much like this app, its very fast! Underappreciated in the community for how well it works, imo.

**Comment by amiralitaheri** [comment]
@exdysa Thanks for sharing that image
Happy to say that
1- The image was using some unsupported comfy UI nodes that caused your image not being add to DB. I Fixed it and now you can see the image but still can't see the prompt because you are using `Any Switch (rgthree)` node. I will try to improve comfy UI parser if the app gets more users but for now we are using some modified version of civitai code.
2- I added [electron-log](https://www.npmjs.com/package/electron-log) so it's easier to identify the image with problem. I will try to add some UI for sharing it as well but for now You can see error logs for importing and syncing in `~/Library/Logs/SD Gallery/main.log`.

I close this issue for now but feel free to reopen it or create a new one.
